name: Git Practice CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current branch
        run: |
          echo "Branch name: ${{ github.ref_name }}"

      - name: Run secret checker script
        run: ./scripts/check-secret.sh

